### ISSUE TITLE
genhtml_edit.py throws an error when trying to open a file

### ISSUE THREAD

**Issue by cjk137** [CuriousNekomimi/AIDCAT#3]
Welcome to the AIDCAT HTML Generator!
First we'll ask for your Adventure file, press Enter to continue...
Traceback (most recent call last):
  File "C:\Users\Me\Documents\AIDungeonRescue-main\aidcat\genhtml_edit.py", line 51, in <module>
    infile = json.load(file)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp932' codec can't decode byte 0x9d in position 119195: illegal multibyte sequence

**Comment by KoboldAI** [comment]
Hi! I'm not Mimi so I can't push a fix to the Git, but I'm dropping a tweak to genhtml_edit.py here that should open your files in binary mode to (hopefully) address the decode error you're getting. (Had to zip it because GitHub wont let me attach the file directly. Unzip it to your AIDCAT directory and overwrite the existing genhtml_edit.py file.)
[genhtml_edit.zip](https://github.com/CuriousNekomimi/AIDCAT/files/6488336/genhtml_edit.zip)
